### ISSUE TITLE
Gnumeric can't create a chart

### ISSUE THREAD

**Issue by SebastianMpl** [ivan-hc/Gnumeric-appimage#1]
Hi,

In the latest Appimage I found that when clicking the chart option I can't make any charts. All options are black and no preview.
When I open a xlsx file with charts they also aren't displayed. Everything else works fine.
Maybe there's some plugin missing?
Could you please check it?

Thank you,

**Comment by ivan-hc** [comment]
> In the latest Appimage

did it worked before?

**Comment by ivan-hc** [comment]
also, run the AppImage from the terminal, so I can read the log...
```
./*.AppImage
```
...and maybe also with LD_DEBUG enabled, for example, to understant what are the missing libraries
```
LD_DEBUG=libs ./*.AppImage
```
let me know the error messages when you try to do the things that are not working.

**Comment by ivan-hc** [comment]
I have just done a test by including all dependences (normally I only select some libraries) and I was able to create charts.

https://github.com/ivan-hc/Gnumeric-appimage/commit/42b7df01994185d7525069c59269f57361556522

Next release should work better, its 23 MB bigger btw https://github.com/ivan-hc/Gnumeric-appimage/releases/tag/continuous

Using [AM](https://github.com/ivan-hc/AM), just run `am -u` or `am -u --apps` or `am -u gnumeric` to update all apps or just it.

**Comment by ivan-hc** [comment]
Close this if it fixes your issue.

**Comment by SebastianMpl** [comment]
Wow, you are so quick that I didn't even have time to upload screenshot.
Yes, charts in new appimage are working great. Thank you very much for quick update.
